# Generated by Django 3.2.5 on 2021-10-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='パターン名')),
                ('Lv50Atk', models.IntegerField(blank=True, verbose_name='★1攻撃力')),
                ('Lv55Atk', models.IntegerField(blank=True, verbose_name='★2攻撃力')),
                ('Lv60Atk', models.IntegerField(blank=True, verbose_name='★3攻撃力')),
                ('Lv65Atk', models.IntegerField(blank=True, verbose_name='★4攻撃力')),
                ('Lv70Atk', models.IntegerField(blank=True, verbose_name='★5攻撃力')),
                ('Lv75Atk', models.IntegerField(blank=True, verbose_name='★6攻撃力')),
                ('Lv80Atk', models.IntegerField(blank=True, verbose_name='★7攻撃力')),
                ('Lv85Atk', models.IntegerField(blank=True, verbose_name='★8攻撃力')),
                ('Lv90Atk', models.IntegerField(blank=True, verbose_name='★9攻撃力')),
                ('Lv95Atk', models.IntegerField(blank=True, verbose_name='★10攻撃力')),
                ('Lv100Atk', models.IntegerField(blank=True, verbose_name='★11攻撃力')),
            ],
            options={
                'verbose_name': '攻撃力パターン',
                'verbose_name_plural': '攻撃力パターン',
            },
        ),
        migrations.CreateModel(
            name='SkillCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='条件名')),
            ],
            options={
                'verbose_name': 'スキル条件',
                'verbose_name_plural': 'スキル条件',
            },
        ),
        migrations.CreateModel(
            name='SkillEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='効果名')),
            ],
            options={
                'verbose_name': 'スキル効果',
                'verbose_name_plural': 'スキル効果',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='作品名')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='キャラクター名')),
                ('Work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card.work', verbose_name='作品')),
            ],
            options={
                'verbose_name': 'キャラクター',
                'verbose_name_plural': 'キャラクター',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1024, verbose_name='カード名')),
                ('Number', models.CharField(blank=True, max_length=64, verbose_name='カード番号')),
                ('Rare', models.IntegerField(choices=[(0, '未選択'), (1, 'N'), (2, 'R'), (3, 'SR'), (4, 'SR+'), (5, 'SSR')], default=0, verbose_name='レアリティ')),
                ('Type', models.IntegerField(choices=[(0, '未選択'), (1, 'FIRE'), (2, 'AQUA'), (3, 'LEAF')], default=0, verbose_name='属性')),
                ('Date', models.DateField(blank=True, verbose_name='追加日')),
                ('SkillName', models.CharField(blank=True, default='', max_length=256, verbose_name='スキル名')),
                ('SkillText', models.TextField(blank=True, default='', verbose_name='スキル効果テキスト')),
                ('SkillName2', models.CharField(blank=True, default='', max_length=256, verbose_name='超開花スキル名')),
                ('SkillText2', models.TextField(blank=True, default='', verbose_name='超開花スキル効果テキスト')),
                ('SkillParamA', models.IntegerField(default=0, verbose_name='スキル効果1効果値')),
                ('SkillParamA2', models.IntegerField(default=0, verbose_name='スキル効果1超開花効果値')),
                ('SkillParamB', models.IntegerField(default=0, verbose_name='スキル効果2効果値')),
                ('SkillParamB2', models.IntegerField(default=0, verbose_name='スキル効果2超開花効果値')),
                ('HowToGet', models.CharField(blank=True, max_length=256, verbose_name='入手方法')),
                ('HowToGet2', models.TextField(blank=True, max_length=256, verbose_name='入手方法詳細')),
                ('Atk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card.attack', verbose_name='攻撃力パターン')),
                ('Character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card.character', verbose_name='作品')),
                ('SkillConditionA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillA_list', to='card.skillcondition', verbose_name='スキル効果1条件')),
                ('SkillConditionB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillB_list', to='card.skillcondition', verbose_name='スキル効果2条件')),
                ('SkillEffectA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillA_list', to='card.skilleffect', verbose_name='スキル効果1')),
                ('SkillEffectB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillB_list', to='card.skilleffect', verbose_name='スキル効果2')),
            ],
            options={
                'verbose_name': 'カード',
                'verbose_name_plural': 'カード',
            },
        ),
    ]
