# Generated by Django 3.2.5 on 2021-10-21 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='SkillConditionA',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillConditionB',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillEffectA',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillEffectB',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillName',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillName2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillParamA',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillParamA2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillParamB',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillParamB2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillText',
        ),
        migrations.RemoveField(
            model_name='card',
            name='SkillText2',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SkillName', models.CharField(blank=True, default='', max_length=256, verbose_name='スキル名')),
                ('SkillText', models.TextField(blank=True, default='', verbose_name='スキル効果テキスト')),
                ('SkillName2', models.CharField(blank=True, default='', max_length=256, verbose_name='超開花スキル名')),
                ('SkillText2', models.TextField(blank=True, default='', verbose_name='超開花スキル効果テキスト')),
                ('SkillParamA', models.IntegerField(default=0, verbose_name='スキル効果1効果値')),
                ('SkillParamA2', models.IntegerField(default=0, verbose_name='スキル効果1超開花効果値')),
                ('SkillParamB', models.IntegerField(default=0, verbose_name='スキル効果2効果値')),
                ('SkillParamB2', models.IntegerField(default=0, verbose_name='スキル効果2超開花効果値')),
                ('SkillConditionA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillA_list', to='card.skillcondition', verbose_name='スキル効果1条件')),
                ('SkillConditionB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillB_list', to='card.skillcondition', verbose_name='スキル効果2条件')),
                ('SkillEffectA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillA_list', to='card.skilleffect', verbose_name='スキル効果1')),
                ('SkillEffectB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillB_list', to='card.skilleffect', verbose_name='スキル効果2')),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='Skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card.skill', verbose_name='スキル'),
        ),
    ]
