# Generated by Django 3.2.5 on 2021-10-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20211021_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='Lv100Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★11攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv50Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★1攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv55Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★2攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv60Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★3攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv65Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★4攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv70Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★5攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv75Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★6攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv80Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★7攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv85Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★8攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv90Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★9攻撃力'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='Lv95Atk',
            field=models.IntegerField(blank=True, default=0, verbose_name='★10攻撃力'),
        ),
    ]
