# Generated by Django 3.2.5 on 2021-10-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20211021_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='Rare',
            field=models.IntegerField(choices=[(0, '未選択'), (1, 'ATTACK'), (2, 'BOOST'), (3, 'ASSIST'), (4, 'GUARD')], default=0, verbose_name='スキル種別'),
        ),
    ]
