# Generated by Django 3.2.5 on 2021-10-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_skill_rare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='Rare',
            new_name='Type',
        ),
        migrations.AddField(
            model_name='skill',
            name='Name',
            field=models.CharField(default='あ', max_length=1024, verbose_name='スキル名(判別用)'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SkillConditionA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillA_list', to='card.skillcondition', verbose_name='スキル効果1条件'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SkillConditionB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillB_list', to='card.skillcondition', verbose_name='スキル効果2条件'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SkillEffectA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillA_list', to='card.skilleffect', verbose_name='スキル効果1'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='SkillEffectB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillB_list', to='card.skilleffect', verbose_name='スキル効果2'),
        ),
    ]
