# Generated by Django 3.2.5 on 2021-10-21 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20211021_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Atk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.attack', verbose_name='攻撃力パターン'),
        ),
        migrations.AlterField(
            model_name='card',
            name='Character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.character', verbose_name='作品'),
        ),
        migrations.AlterField(
            model_name='card',
            name='Date',
            field=models.DateField(blank=True, null=True, verbose_name='追加日'),
        ),
        migrations.AlterField(
            model_name='card',
            name='Skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.skill', verbose_name='スキル'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='Name',
            field=models.CharField(max_length=1024, verbose_name='スキル名(判別用)'),
        ),
    ]
